es:
  host: '192.168.0.64'
  port: '9200'
  cluster: 'superheromatch'
  index: 'superhero'

db:
  host: '192.168.0.64'
  port: 3306
  user: 'dev'
  password: 'Awesome85**'
  name: 'municipality'
  limit: 50